### ISSUE TITLE
Does this require the Jemalloc-rb Gem to be installed in our Gemfile?

### ISSUE THREAD

**Issue by tonydehnke** [gaffneyc/heroku-buildpack-jemalloc#18]
Hi, not totally clear (and I'm in a bit over my head here). If we want to use this with our current Rails app - do we need to install the ruby Jemalloc gem as well?   

It would be good if the readme could specify that.

(PS - was not sure where else to ask, so posting this here).

**Comment by gaffneyc** [comment]
No, the jemalloc gem conflicts with the buildpack as it bundles in a very old version of jemalloc.

That's a good question and something we should note in the README.

**Comment by tonydehnke** [comment]
Awesome - thank you for the prompt reply.   Reading up on this and learning (I'm a newbie)..  Can we just run this on Heroku, or do we need to update our local environments to run Jemalloc too (seen some posts about how to install Ruby and force it to use Jemalloc).  

Thanks!

**Comment by gaffneyc** [comment]
Yep, you can just run it on Heroku and don't need to make any changes to your local environment. The benefits you would see from jemalloc show up more in production compared to development since you're dealing with production level traffic and you have long running processes.

**Comment by tonydehnke** [comment]
Thank you!  Should we add that to a FAQ or the readme?  (Or would most people looking into this already know that?)
