### ISSUE TITLE
Invalidate the cache on stack upgrade

### ISSUE THREAD

**Issue by edmorley** [gaffneyc/heroku-buildpack-jemalloc#19]
Hi!

Thank you for adding support for Heroku-20 so fast (https://github.com/gaffneyc/heroku-buildpack-jemalloc/commit/1e33801059ad09c83535d16ec1c8652996464f56).

I noticed that currently the buildpack doesn't invalidate the cache when the app's `$STACK` changes, which would presumably cause issues depending on whether it's a stack upgrade or downgrade, and what ABI differences exist between stacks.

A possible pattern for solving this would be:
https://github.com/heroku/heroku-buildpack-apt/blob/0357ec1e8863a803ada6c2d57f0850f2c5fa0366/bin/compile#L32-L41

Many thanks :-)

**Comment by gaffneyc** [comment]
Good catch! I originally had a plan for stack changes but it got lost in the implementation.

I've pushed #20 based on the pattern from heroku-buildpack-apt and need to test it with a deploy before merging.

Thanks!

**Comment by gaffneyc** [comment]
@edmorley Thanks again for the report and the suggested fix

**Comment by edmorley** [comment]
@gaffneyc Thank you for the quick fix! :-)
