### ISSUE TITLE
bundle command not found

### ISSUE THREAD

**Issue by kevinhq** [gaffneyc/heroku-buildpack-jemalloc#22]
Using this buildpack caused our Rails app on Heroku-20 stack crashed with error: bundle command not found.

stack:
- ruby 2.7.3
- rails 6.1.1

decide to revert to heroku/ruby buildpack for now

**Comment by kevinhq** [comment]
here's the test app: https://github.com/kevinhq/jemalloc-test-heroku. just deploy it to heroku for free.

**Comment by gaffneyc** [comment]
```decide to revert to heroku/ruby buildpack for now```

You need to use this buildpack _in addition to_ the heroku/ruby buildpack.

For example, this is the output of the `heroku buildpacks` command run for one of our Rails apps:
```
heroku buildpacks -a [redacted]
=== [redacted] Buildpack URLs
1. https://github.com/gaffneyc/heroku-buildpack-jemalloc.git
2. https://github.com/deadmanssnitch/heroku-buildpack-dms
3. heroku/nodejs
4. heroku/ruby
```

**Comment by kevinhq** [comment]
yes. i've figured it out. thanks
