### ISSUE TITLE
Request: add support for latest heroku-24 stack

### ISSUE THREAD

**Issue by greghuc** [gaffneyc/heroku-buildpack-jemalloc#35]
Hi there

Heroku-24 stack is now [generally available](https://devcenter.heroku.com/changelog-items/2898).

Could this new stack please be supported by heroku-buildpack-jemalloc?

Many thanks

Greg

**Comment by gaffneyc** [comment]
Since c125b14109c65e59972383661093aee394ed9ada we shouldn't need to make any changes for the heroku-24 stack since we now compile jemalloc during the build phase. Are you seeing something fail? I haven't tried updating an app to heroku-24 yet so I haven't tested it myself.

I know some folks have pinned to a specific commit so it might be worth building packages from heroku-24.

**Comment by greghuc** [comment]
@gaffneyc thanks for the clarification. I haven't tried heroku-24 yet, as I assumed that the jemalloc buildpack was a blocker. Based on the 'Building' section at the bottom of the README, and there being a 'releases' area, I presumed a build was needed to release on heroku-24.

WIll try a deploy tomorrow and report back.

**Comment by gaffneyc** [comment]
@greghuc Probably time to clean that up since we no longer need to build releases for new stacks. I'm going to wait to build it until someone comes forward who is pinned to an old commit of the buildpack.

**Comment by gaffneyc** [comment]
I tried to deploy an app to `heroku-24` and the jemalloc install went just fine... but ran into an error in the Ruby buildpack so couldn't validate it.

**Comment by greghuc** [comment]
OK, I successfully deployed heroku-24 + jemalloc-buildpack to my main staging environment. Seems fine - I saw jemalloc download src and recompile.

I reckon it's all good.

Feel free to close this ticket when you see fit.

Many thanks!

**Comment by greghuc** [comment]
FYI been running heroku-24 + jemalloc-buildpack in production since last week, and all looks good.

**Comment by gaffneyc** [comment]
Great! Thanks for following up
