### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tylerjolmstead** [gaffneyc/heroku-buildpack-jemalloc#4]
Thank you for this very helpful buildpack! Would you mind including a license file to be explicit about the terms under which your contributions are licensed? [mojodna/heroku-buildpack-jemalloc](https://github.com/mojodna/heroku-buildpack-jemalloc) is currently BSD licensed.

https://github.com/mojodna/heroku-buildpack-jemalloc/blob/master/LICENSE

**Comment by gaffneyc** [comment]
Thanks, I'm glad you're finding it useful. We'll add the BSD-3 clause similar to what mojodna added to the upstream repo.

Main reason I haven't done it yet was I forked the repo prior to when the license was added and basically did a complete rewrite, so I wasn't sure what made sense.
