### ISSUE TITLE
How to validate buildpack is having an effect

### ISSUE THREAD

**Issue by ncri** [gaffneyc/heroku-buildpack-jemalloc#5]
Just a quick question how to validate the buildpack is in effect. I tried what's suggested in some places:

```
ruby -r rbconfig -e "puts RbConfig::CONFIG['LIBS']"
```

But this only gives me:

```
-lpthread -lgmp -ldl -lcrypt -lm 
```

Although the buildpack seems to do something, as I saw a pthread error similar to the one in https://github.com/gaffneyc/heroku-buildpack-jemalloc/issues/3 and had to revert to version 5.0.1 as suggested to make it go away.

**Comment by gaffneyc** [comment]
There was a long discussion in mojodna/heroku-buildpack-jemalloc/issues/6 but I don't believe anyone came up with a good answer.

The most correct answer would probably involve dropping into C to check if some the jemalloc functions were defined or the lib was loaded (this is beyond my depth).

A niece approach would be to check the LD_PRELOAD is being set (below). This won't work if the library doesn't exist (which was an issue before JEMALLOC_ENABLED was an option).

```ruby
/jemalloc/.match?(ENV["LD_PRELOAD"])
```

**Comment by ncri** [comment]
Okay, thx!

**Comment by johnsudaar** [comment]
A good way i found on https://github.com/docker-library/ruby/issues/182#issuecomment-457616010 is using:

```
MALLOC_CONF=stats_print:true ruby -e "exit"
```
If jemalloc is activated it will generate the jemalloc stats overwise it will just exit.
